### ISSUE TITLE
Restore fails

### ISSUE THREAD

**Issue by andrewrynhard** [FiloSottile/gvt#33] opened 2016-04-16 23:29 UTC
Get the following error when trying to restore from `vendor/manifest`

```
$ go version
go version go1.6 darwin/amd64
```

```
$ gvt restore
2016/04/16 16:26:34 fetching github.com/andrewrynhard/go-mask 
2016/04/16 16:26:34 fetching golang.org/x/crypto/ssh/terminal 
2016/04/16 16:26:34 fetching golang.org/x/crypto/cast5 
2016/04/16 16:26:34 fetching golang.org/x/crypto/openpgp 
2016/04/16 16:26:34 fetching github.com/codegangsta/cli 
2016/04/16 16:26:34 fetching github.com/libgit2/git2go 
2016/04/16 16:26:34 fetching golang.org/x/crypto/openpgp/armor 
2016/04/16 16:26:34 fetching golang.org/x/crypto/openpgp/packet 
2016/04/16 16:26:37 fetching gopkg.in/yaml.v2 
2016/04/16 16:26:37 golang.org/x/crypto/openpgp: dependency could not be deleted: remove /Users/andrewrynhard/Desktop/go/src/github.com/autonomy/alterant/vendor/golang.org/x/crypto/openpgp/packet: directory not empty
2016/04/16 16:26:44 command "restore" failed: failed to fetch 1 dependencies
```

MANIFEST:

```
{
    "version": 0,
    "dependencies": [
        {
            "importpath": "github.com/andrewrynhard/go-mask",
            "repository": "https://github.com/andrewrynhard/go-mask",
            "vcs": "git",
            "revision": "6d3ea05f56fa3bd7328b44ac5caf4359423edaf2",
            "branch": "master",
            "notests": true
        },
        {
            "importpath": "github.com/codegangsta/cli",
            "repository": "https://github.com/codegangsta/cli",
            "vcs": "git",
            "revision": "71f57d300dd6a780ac1856c005c4b518cfd498ec",
            "branch": "master",
            "notests": true
        },
        {
            "importpath": "github.com/libgit2/git2go",
            "repository": "https://github.com/libgit2/git2go",
            "vcs": "git",
            "revision": "95793ac11dbca2f35770c690d9ba7e64d7018815",
            "branch": "master",
            "notests": true
        },
        {
            "importpath": "golang.org/x/crypto/cast5",
            "repository": "https://go.googlesource.com/crypto",
            "vcs": "git",
            "revision": "1777f3ba8c1fed80fcaec3317e3aaa4f627764d2",
            "branch": "master",
            "path": "/cast5",
            "notests": true
        },
        {
            "importpath": "golang.org/x/crypto/openpgp",
            "repository": "https://go.googlesource.com/crypto",
            "vcs": "git",
            "revision": "1777f3ba8c1fed80fcaec3317e3aaa4f627764d2",
            "branch": "master",
            "path": "/openpgp",
            "notests": true
        },
        {
            "importpath": "golang.org/x/crypto/openpgp/armor",
            "repository": "https://go.googlesource.com/crypto",
            "vcs": "git",
            "revision": "1777f3ba8c1fed80fcaec3317e3aaa4f627764d2",
            "branch": "master",
            "path": "/openpgp/armor",
            "notests": true
        },
        {
            "importpath": "golang.org/x/crypto/openpgp/packet",
            "repository": "https://go.googlesource.com/crypto",
            "vcs": "git",
            "revision": "1777f3ba8c1fed80fcaec3317e3aaa4f627764d2",
            "branch": "master",
            "path": "/openpgp/packet",
            "notests": true
        },
        {
            "importpath": "golang.org/x/crypto/ssh/terminal",
            "repository": "https://go.googlesource.com/crypto",
            "vcs": "git",
            "revision": "1777f3ba8c1fed80fcaec3317e3aaa4f627764d2",
            "branch": "master",
            "path": "/ssh/terminal",
            "notests": true
        },
        {
            "importpath": "gopkg.in/yaml.v2",
            "repository": "https://gopkg.in/yaml.v2",
            "vcs": "git",
            "revision": "a83829b6f1293c91addabc89d0571c246397bbf4",
            "branch": "master",
            "notests": true
        }
    ]
}
```

**Comment by FiloSottile** [comment] 2016-04-18 01:22
Thanks for the report, this is caused by the overlapping `golang.org/x/crypto/openpgp/packet` and `golang.org/x/crypto/openpgp` deps.

Closing as a duplicate on #32, and bumping up the priority of that.

**Closed as completed by FiloSottile** 2016-04-18 01:22 UTC
Labels: duplicate
