### ISSUE TITLE
gvt delete doesn't remove recursive dependencies

### ISSUE THREAD

**Issue by ghost** [FiloSottile/gvt#47] opened 2016-05-05 11:49 UTC
I did `gvt fetch github.com/nstogner/httpware` and it also fetched 'github.com/Sirupsen/logrus' but then when I did `gvt delete github.com/nstogner/httpware` the logrus dependency was still intact. Is this the way its supposed to be?

**Comment by FiloSottile** [comment] 2016-07-28 02:16
Duplicate of #16

**Closed as completed by FiloSottile** 2016-07-28 02:16 UTC
Labels: duplicate
