### ISSUE TITLE
Does not pick up internal packages

### ISSUE THREAD

**Issue by AudriusButkevicius** [FiloSottile/gvt#35] opened 2016-04-17 13:55 UTC
```
Audrius@Audrius foo $ gvt fetch golang.org/x/text/unicode/norm
2016/04/17 14:54:34 fetching recursive dependency golang.org/x/text/transform
Audrius@Audrius foo $ cat ./vendor/golang.org/x/text/unicode/norm/maketables.go | grep internal
        "golang.org/x/text/internal/gen"
        "golang.org/x/text/internal/triegen"
        "golang.org/x/text/internal/ucd"
Audrius@Audrius foo $ ls ./vendor/golang.org/x/text/internal
ls: cannot access ./vendor/golang.org/x/text/internal: No such file or directory
```

**Comment by FiloSottile** [comment] 2016-05-10 20:22
The problem here is the build tag at the top of `maketables.go`

**Comment by FiloSottile** [comment] 2016-05-10 20:23
Closing as duplicate of #34

**Closed as completed by FiloSottile** 2016-05-10 20:23 UTC
